### ISSUE TITLE
Feature request: upload files by path using sendfile

### ISSUE THREAD

**Issue by mikpe** [aws-beam/aws-erlang#106]
I recently asked our local aws-erlang users if a file to S3 upload could avoid reading the file's contents first and instead stream it using something like Linux' sendfile. Alas the answer I got was that this project doesn't support that.

Hence this is a request to enable that feature.

**Comment by onno-vos-dev** [comment]
Hi @mikpe, 

Considering the fact that the Body of a request is part of the V4 Signature that is sent to AWS, one has to have a Body that contains the data to be sent to AWS. Looking at `aws-sdk-js` (one of the easiest SDK's to follow IMHO), they seem to solve this by setting up a fileStream and simply reading chunks from that stream to be sent across the wire using a multipart upload. 

This would also be possible using aws-erlang as multipart uploading is supported by using `aws_s3:create_multipart_upload/5` followed by `aws_s3:upload_part/5` and a `aws_s3:complete_multipart_upload/5` to complete it once all chunks of data has been sent. This would at least avoid pulling the entire file into the application at once in case you're trying to upload a large file. Would that be an acceptable behavior for you @mikpe? 

`aws-erlang` does not support such functionality out of the box at least. Considering `aws-erlang` is a auto-generated library based off the `aws-sdk-go` injecting specific code into a specific module (`aws-s3`) and would require a decent chunk of work to add support for such a feature. Adding the functionality to implement this sort of chunked reading would be fairly trivial, it'd have to be hooked somehow into the `aws-codegen` which will be the tricky part. 

I'll need to do some thinking on how to hook this in.

**Comment by mikpe** [comment]
The multipart upload approach would help a bit. The sendfile approach is more of a wishlist item than a requirement.

**Comment by mikpe** [comment]
I looked over some AWS S3 docs and it doesn't seem possible to upload files with sendfile, since each upload method (whether multipart or not) requires an md5sum of the data up-front.

So I'm closing this feature request.
