### ISSUE TITLE
aws_request:sign_request/5 fails due to undefined value for service in aws_client map

### ISSUE THREAD

**Issue by MrAlgorithms** [aws-beam/aws-erlang#4]
When making a Client, the **service** map entry gets set to **undefined**. This causes an error when making a request, but more specifically when  **aws_util:binary_join/3** gets hit in **aws_util:credential_scope/3**. Perhaps the aws_client interface should allow for the service to be set?

To reproduce...
1. use **aws_client:make_temporary_client** to make a client
2. use **aws_request:sign_request** to sign request

Result: 
** exception error: bad argument
     in function  bit_size/1
        called as bit_size(undefined)
     in call from aws_util:binary_join/3 (***/aws-erlang/_build/default/lib/aws/src/aws_util.erl, line 51)
     in call from aws_request:sign_request/10 (***/aws-erlang/_build/default/lib/aws/src/aws_request.erl, line 38)

**Comment by jfacorro** [comment]
@MrAlgorithms AFAIU the `service` entry in the `aws_client` map is meant to be set by each implementation module (e.g. [here](https://github.com/aws-beam/aws-erlang/blob/master/src/aws_ssm.erl#L1780)).

Are you by any chance trying to use the `aws_client` on its own without going through any of the implementation modules?

**Comment by MrAlgorithms** [comment]
Good to know. That was probably it. Thank you.
