### ISSUE TITLE
Handle map-like types in api requests

### ISSUE THREAD

**Issue by mwik** [aws-beam/aws-erlang#49]
For instance when creating a user with tags you have to put the tags like so
```
aws_iam:create_user(Client, #{<<"UserName">> => <<"Name">>, <<"Tag.member.1.Key">> => <<"env">>, <<"Tag.member.1.Value">> => <<"development">>})
```
It would be nice if we could support adding the tags as a map like
```
<<"Tags">> => #{<<"Key1">> => <<"Value1">>}}
```
Or more closely follow the json structure in the [api specification](https://github.com/aws/aws-sdk-go/blob/main/models/apis/iam/2010-05-08/api-2.json#L2871)
```
<<"Tags">> => [#{<<"Key">> => <<"Key1">>,<<"Value">> => <<"Value1">>}]}
```

**Comment by onno-vos-dev** [comment]
@mwik Sorry for leaving this issue hanging for so long, I was actually looking at this today and seeing if something can be done as I agree that it's somewhat wonky. 

Unfortunately, AWS is somewhat inconsistent in their Tagging schema and for example [CreateUser](https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateUser.html) uses a `Tags.member.N` style of tagging. While some APIs use a totally different style such as [PutObjectTagging](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObjectTagging.html) which uses a `TagSet` with several `Tag` elements. Which would require an `Input` in the form of:
```erlang
#{<<"TagSet">> => [{<<"Tag">>, [{<<"Key">>, <<"tag1">>}, {<<"Value">>, <<"val1">>}]}, {<<"Tag">>, [{<<"Key">>, <<"tag2">>}, {<<"Value">>, <<"val2">>}]}]}
```

Seeing as there's essentially two forms and no easy way of knowing which form to user any form of logic to handle more a generic structure would be very difficult as it'd depend on the API and what it should then be transformed into. 

I'm gonna close this issue as I really don't see how we can possibly implement a generic way other than somehow traversing the `api-2.json` such that [api-2.json#L7864](https://github.com/aws/aws-sdk-go/blob/main/models/apis/s3/2006-03-01/api-2.json#L7864) is used to create some conditional logic for determining which style of tags to transform into which will be a gigantic mess in aws-codegen IF at all possible without turning it into spaghetti bolognese. :smile:

**Comment by mwik** [comment]
Sounds reasonable. Anyway, thank you for looking into it.
