### ISSUE TITLE
API codegen / Feature Request: Lambda

### ISSUE THREAD

**Issue by paulreimer** [aws-beam/aws-erlang#5]
The lambda API combined with Erlang is very useful (to me, at least!); it saves the hassle of provisioning/paying for an API Gateway when I want to invoke lambdas directly from Erlang using AWS creds/perms.

**Comment by jfacorro** [comment]
This will be possible once aws-beam/aws-codegen#12 is done.

**Comment by jfacorro** [comment]
There is now support for AWS Lambda. 🥳 

We will create a new release and publish it to hex.
