### ISSUE TITLE
Create release and publish

### ISSUE THREAD

**Issue by jfacorro** [aws-beam/aws-erlang#8]
The [`aws_erlang`](https://hex.pm/packages/aws_erlang) hex package is owned by @talentdeficit, once the release is created we should reach out and ask them to publish the new version.

**Comment by mrallen1** [comment]
Hm. I thought our hex package name was `aws` but... maybe I am wrong.

**Comment by jfacorro** [comment]
No, you are right, the Elixir package is `aws` but from what I could find the Erlang package `aws_erlang` is the one for the aws-erlang repository. Maybe I'm missing something or getting confused?

**Comment by mrallen1** [comment]
Ah, yeah I guess I didn't notice the repo this issue is filed on 😄  Sorry...

**Comment by talentdeficit** [comment]
i completely forgot i was the one who initially published that repo. i'd be happy to hand it off to someone else who'll be more active in maintaining it

**Comment by jfacorro** [comment]
@talentdeficit I would be willing to take that off your hands 😄 , let me know what you need for that to happen.

**Comment by talentdeficit** [comment]
@jfacorro done. i transferred it to the account with the username @jfacorro on hex (the same one that "owns" `aws` on hex)

**Comment by jfacorro** [comment]
@talentdeficit Thank you! 🙏
